<table class="table">
	<thead>
		<tr>
			<th>Partner ID</th>
			<th>Name</th>
			<th>Status</th>
		</tr>
	</thead>
	
	
	<tbody>
	<?php if(!empty($this->partners)):?>
		<?php foreach ($this->partners as $row):?>
			<tr>
				<td><?php echo $row['partnerid'];?></td>
				<td><?php echo $row['partner_name'];?></td>
				<td><?php echo $row['status'] == 1 ? "Active" : "Not Active";?></td>
			</tr>
		<?php endforeach;?>
	<?php else:?>
		<tr>
			<td colspan="3">
				No users for selected params
			</td>
		</tr>
	<?php endif;?>
	<tr>
		<td colspan="3">
			<?php echo $this->render('partial/pagination.phtml');?>
		</td>
	</tr>

	</tbody>
</table>