<?php echo $this->render('common/header.phtml');?>

</head>
<body>

<?php echo $this->render('common/topmenu.phtml');?>

<div class="container main">
<div class="row well">
  <div class="col-md-12">
 
	  <h1><?php echo $this->message ?></h1>
	
	  <?php if (isset($this->exception)): ?>
	  
	  <h3><?php echo $this->translate('Exception information:')?></h3>
	  <p>
	      <b><?php echo $this->translate('Message:')?></b> <?php echo $this->exception->getMessage() ?>
	  </p>
	
	  <h3><?php echo $this->translate('Stack trace:')?></h3>
	  <pre><?php echo $this->exception->getTraceAsString() ?>
	  </pre>
	
	  <h3><?php echo $this->translate('Request Parameters:')?></h3>
	  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
	  </pre>
	
	  <?php endif ?>

  </div>
</div>
</div>


</body>

</html>


 
