<?php echo $this->render('common/header_cms.phtml');?>

</head>
<body>
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.main.js"></script>
	
	<?php echo $this->render('common/cmsmenu.phtml');?>

	<div data-msgholder class="msgholder app-error-container"></div>

	<div style="display: none;" class="" id="loading">			
		<div class="loader">				
			<h3>Please wait...</h3>
			<img src="<?php echo $this->baseUrl();?>/images/loader.gif" alt="Please wait..." class="centerLoader">			
		</div>		
	</div>
	
	<div class="mainmenu-holder">
		
	</div>

	<div class="">
	
		<iframe id="siteframe" src="http://sitecms.intra"></iframe>
	
	</div> <!-- end container -->
<?php echo $this->render('common/end.phtml');?>


 
