<?php echo $this->render('common/header.phtml');?>

</head>
<body>

	<?php //echo $this->render('common/topmenu.phtml');?>

	<div data-msgholder class="msgholder app-error-container"></div>

	<div style="display: none;" class="" id="loading">			
		<div class="loader">				
			<h3>Please wait...</h3>
			<img src="<?php echo $this->baseUrl();?>/images/loader.gif" alt="Please wait..." class="centerLoader">			
		</div>		
	</div>

	<div class="">
	
		<div class="row">
			
				<iframe id="site_frame" src="http://sitecms.intra/about"></iframe>
				
		</div>
	
	</div> <!-- end container -->

<?php //echo $this->render('common/end.phtml');?>


 
