<!DOCTYPE html>
<html>
<head>
    <title>CMS Site Editor</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	
	<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
	<!--[if lt IE 9]><script src="<?php echo $this->baseUrl()?>/include/html5shiv/dist/html5shiv.js"></script><![endif]-->
	
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.core.loader.js"></script>
	
	<!-- jQuery -->
	
	<link rel="stylesheet" media="screen" type="text/css" href="<?php echo $this->baseUrl()?>/include/jQuery/css/ui-lightness/jquery-ui-1.8.23.custom.css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">

	<!-- bootstrap -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.min.css">
	
	<!-- load standard css -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/ie-fix.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/editorstyle.css">