<!DOCTYPE html>
<html>
<head>
    <title>CMS Site Editor</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	
	<!-- Shim to make HTML5 elements usable in older Internet Explorer versions -->
	<!--[if lt IE 9]><script src="<?php echo $this->baseUrl()?>/include/html5shiv/dist/html5shiv.js"></script><![endif]-->

	<!-- jQuery -->
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/jQuery/jquery-1.8.0.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/include/jQuery/jquery-ui-1.8.23.custom.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/scripts/jquery-ui.min.js"></script>
	
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/scripts/underscore.min.js"></script>
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/scripts/backbone.min.js"></script>
	
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.events.js"></script>
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.main.js"></script>
	
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.models.base.js"></script>
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.models.js"></script>
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.views.base.js"></script>
	<script type ="text/javascript" src="<?php echo $this->baseUrl()?>/js/cms/cms.views.js"></script>
	
	<link rel="stylesheet" media="screen" type="text/css" href="<?php echo $this->baseUrl()?>/include/jQuery/css/ui-lightness/jquery-ui-1.8.23.custom.css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
	<script>
		var php_baseUrl = "<?php echo $this->baseUrl();?>";
		$(document).ready(function(){
			$('#myTab a').click(function (e) {
			    e.preventDefault();
			    $(this).tab('show');
		    })
		});
	</script>

	<!-- bootstrap -->
	<script src="<?php echo $this->baseUrl()?>/bootstrap/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.min.css">
	
	<!-- load standard css -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/ie-fix.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/style.css">