<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->sitedata["title"];?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta charset="utf-8">
	
	<link rel="stylesheet" media="screen" type="text/css" href="<?php echo $this->baseUrl()?>/include/jQuery/css/ui-lightness/jquery-ui-1.8.23.custom.css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
	<script>
		var php_baseUrl = "<?php echo $this->baseUrl();?>";
		$(document).ready(function(){
			$('#myTab a').click(function (e) {
			    e.preventDefault();
			    $(this).tab('show');
		    })
		});
	</script>
	
	<!-- bootstrap -->
	<script src="<?php echo $this->baseUrl()?>/bootstrap/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/bootstrap/css/bootstrap.min.css">
	
	<!-- load standard css -->
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/ie-fix.css">
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl()?>/css/style.css">