<div id="logo"><img src="http://poker.365planet365.com/sites/all/themes/poker/logo.png" alt="" /></div>
<div id="topmenu" class="navbar navbar-inverse" role="navigation">
	<div class="container">

		<div class="navbar-header" style="margin-right: 20px">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a href="<?php echo $this->baseUrl()?>/" class="navbar-brand pull-left">
			<span><?php echo $this->sitedata["title"];?></span>
			</a>
			

		</div>

		<div class="collapse navbar-collapse navbar-ex1-collapse">
		
			<?php foreach ($this->sitedata["menu"] as $k=>$menuitem): ?>
				<ul class="nav navbar-nav navbar-left">
					<li><a href="<?php echo $this->sitedata["siteUrl"];?>/<?php echo $menuitem["url"];?>"><?php echo $menuitem["title"];?></a></li>
				</ul>
			<?php endforeach;?>
		</div>

	</div>
</div>
