<form action="<?php echo $this->escape($this->element->getAction()) ?>" method="<?php echo $this->escape($this->element->getMethod()) ?>" id="<?php echo $this->element->getId(); ?>">

<?php foreach($this->element as $element):?>
<?php if ($element->getId() == 'submitbtn') continue;?>
<div class="form-group <?php echo $element->getId();?>">
<label for="<?php echo $element->getId();?>"><?php echo $element->getLabel(); ?></label>
<?php echo $element->render(); ?>
</div>
<?php endforeach;?>

<hr />

<div class="pull-right">
<span><?php echo $this->element->submitbtn; ?></span>
</div>

</form>
